### ISSUE TITLE
ENABLE_SSH je v zakladu false

### ISSUE THREAD

**Issue by TheDuchy** [haxagoncz/challenge-workstation#1]
Jak si muzeme povsimnout [zde](https://github.com/haxagoncz/challenge-workstation/blob/7284933ed93e3431399b5e25dd94640bb786b514/entrypoint.sh#L29), bez nastaveni ENABLE_SSH na `true` se tento if nikdy nemuze vyhodnotit jako `true`.

Jednoduchy zpusob jak to napravit je zmenit README, kde ENABLE_SSH je v zakladu false. 😄

**Comment by dubblen** [comment]
Je to tak, jak píšeš. Díky :)

Opraveno podle tvého tipu.
